[package]
name = "aegis-idle"
description = "Idle policy coordinator for the Aegis desktop"
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
aegis-model.workspace = true
aegis-ipc.workspace = true
log.workspace = true
aegis-logging.workspace = true
libc.workspace = true
thiserror.workspace = true
wayland-client.workspace = true
wayland-protocols.workspace = true
zbus.workspace = true
