[package]
name = "aegis-avatar"
description = "VRM avatar animation and offscreen rendering"
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
fastrand.workspace = true
flux = { workspace = true }
flux-sys = { workspace = true }
flux-scene-graph = { workspace = true }
flux-scene-graph-sys = { workspace = true }
image = { workspace = true }
log.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile = "3"

[package.metadata.cargo-machete]
ignored = ["flux-scene-graph-sys", "flux-sys"]
