use super::*;

type IconSnapshot = std::collections::BTreeMap<std::path::PathBuf, Option<IconFileStamp>>;
type AppScanResult = (String, Vec<ass_core::app::Entry>, IconSnapshot);

/// Owns the mutable composition state used by the compositor event loop.
///
/// Startup builds this value once, after which event-loop phases borrow only
/// the state they need. Keeping ownership here makes those phases independently
/// testable and prevents the composition root from accumulating more locals.
pub(super) struct CompositorRuntime {
    pub(super) notif_queue: std::sync::Arc<std::sync::Mutex<ass_core::notify::NotificationQueue>>,
    pub(super) config_path: Option<std::path::PathBuf>,
    pub(super) config: Option<ass_config::Config>,
    pub(super) device: flux::Device,
    pub(super) host: Host,
    pub(super) surface: flux::Surface,
    pub(super) canvas: flux::Canvas,
    pub(super) launcher_backdrop: LauncherBackdrop,
    pub(super) pending_capture: Option<PendingCapture>,
    pub(super) capture_worker: CaptureWorker,
    pub(super) cursor_cache: cursor::CursorCache,
    pub(super) screenshot_dir: std::path::PathBuf,
    pub(super) server: ass_server::Server,
    pub(super) icon_theme: String,
    pub(super) icon_scale: u32,
    pub(super) launcher_apps: Vec<ass_core::app::Entry>,
    pub(super) icon_cache: IconCache,
    pub(super) icon_snapshot: IconSnapshot,
    pub(super) shell: ass_shell::Shell,
    pub(super) input_acc: InputAccumulator,
    pub(super) renderer: ass_render::Renderer,
    pub(super) realm_processes: RealmProcesses,
    pub(super) realm_render_targets:
        std::collections::BTreeMap<ass_core::realm::RealmId, RealmRenderTarget>,
    pub(super) pending_realm_capture: Option<PendingRealmCapture>,
    pub(super) realm_damage_sequence: u64,
    pub(super) agent_activity_sequence: u64,
    pub(super) start: std::time::Instant,
    pub(super) wallpaper: Option<ass_wallpaper::Wallpaper>,
    pub(super) clear: u32,
    pub(super) frame_count: u64,
    pub(super) retired_defer: Option<u64>,
    pub(super) super_tap: ass_core::input::TapDetector,
    pub(super) prev_captured: bool,
    pub(super) keymap: ass_core::keybind::Keymap,
    pub(super) system_status: ass_shell::SystemStatus,
    pub(super) status_rx: std::sync::mpsc::Receiver<ass_shell::SystemStatus>,
    pub(super) reload: Option<ass_config::ReloadWatcher>,
    pub(super) quit_requested: bool,
    pub(super) ipc_cmd_rx: std::sync::mpsc::Receiver<IpcCommandRequest>,
    pub(super) capture_rx: std::sync::mpsc::Receiver<CaptureRequest>,
    pub(super) realm_control_rx: std::sync::mpsc::Receiver<RealmControlRequest>,
    pub(super) settings_control_rx: std::sync::mpsc::Receiver<SettingsControlRequest>,
    pub(super) realm_capture_rx: std::sync::mpsc::Receiver<RealmCaptureRequest>,
    pub(super) journal_refusal_rx: std::sync::mpsc::Receiver<JournalRefusalRequest>,
    pub(super) journal: std::sync::Arc<std::sync::Mutex<ass_ipc::Journal>>,
    pub(super) live: std::sync::Arc<LiveState>,
    pub(super) ipc: Option<ass_ipc::Server>,
    pub(super) last_win_sig: Option<Vec<(ass_core::window::WindowId, bool, Option<String>)>>,
    pub(super) last_ws_snap: Option<ass_core::workspace::WorkspaceSnapshot>,
    pub(super) last_realm_revision: Option<u64>,
    pub(super) settings_revision: u64,
    pub(super) previous_agent_suspended: bool,
    pub(super) automatically_paused_realms: std::collections::BTreeSet<ass_core::realm::RealmId>,
    pub(super) animating: bool,
    pub(super) chrome_pointer_captured: bool,
    pub(super) synthetic_pointer_active: bool,
    pub(super) last_cursor_shape: u32,
    pub(super) last_cursor_hidden: bool,
    pub(super) next_app_scan: std::time::Instant,
    pub(super) scan_req_tx: std::sync::mpsc::Sender<u32>,
    pub(super) scan_result_rx: std::sync::mpsc::Receiver<AppScanResult>,
    pub(super) pending_scan_scale: u32,
    pub(super) previous_frame_at: std::time::Instant,
}
