[package]
name = "ass-wallpaper"
description = "Compositor wallpaper: multi-format image and short-video backgrounds"
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
flux = { workspace = true }
flux-scene-graph = { workspace = true }
flux-scene-graph-sys = { workspace = true }
image = { workspace = true }
log.workspace = true
thiserror.workspace = true
