[package]
name = "aegis-compositor"
description = "Hand-rolled Wayland server: socket, globals, and protocol object lifecycle"
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
build = "build.rs"

[dependencies]
aegis-core = { workspace = true }
aegis-protocols = { workspace = true }
log.workspace = true
thiserror.workspace = true
xkbcommon = "0.9"

[build-dependencies]
pkg-config = "0.3"
